server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///dbgirl?characterEncoding=utf8&useSSL=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true